package com.oottru.internationalization.Util

class Constants {

    companion object {
        val baseUrl: String = "http://54.149.178.226/api/"
        var APPLICATION_LABEL = "APPLICATION_LABEL"
        var PROJECT_SINGIN_MESSAGE = "PROJECT_SINGIN_MESSAGE"
        val KEY_TRANSLATION_RESPONSE = "translation"
        var KEY_DETAIL_RESPONSE = "detailresponse"
        val KEY_DEFAULT_LANGUAGE_CODE = "en"
        val LBL_USERNAME: String = "MBL_LBL_USERNAME";
        val LBL_PASSWORD: String = "MBL_LBL_PASSWORD"
        val BTN_SIGNIN: String = "MBL_BTN_LOGIN"
        val MBL_LOGIN_HEAD: String = "MBL_LOGIN_HEAD"
        val MBL_LBL_HOME: String = "MBL_LBL_HOME"
        val MBL_LBL_MACHINESETUP: String = "MBL_LBL_MACHINESETUP"
        val MBL_LBL_CONTACTINFO: String = "MBL_LBL_CONTACTINFO"
        val MBL_LBL_PROFILE: String = "MBL_LBL_PROFILE"
        val MBL_LBL_LANGUAGE: String = "MBL_LBL_LANGUAGE"
        val MBL_LBLSIGNOUT: String = "MBL_LBLSIGNOUT"
        val PROJECT_DETAIL_PROJECT_NAME: String = "PROJECT_DETAIL_PROJECT_NAME"
        val PROJECT_DETAIL_DESCRIPTION: String = "PROJECT_DETAIL_DESCRIPTION"
        val PROJECT_DETAIL_FINISHED_SIZE: String = "PROJECT_DETAIL_FINISHED_SIZE"
        val PROJECT_DETAIL_MATERIALS_TO_CUT: String = "PROJECT_DETAIL_MATERIALS_TO_CUT"
        val PROJECT_DETAIL_EVERYTHING_ELSE_YOU_NEED: String = "PROJECT_DETAIL_EVERYTHING_ELSE_YOU_NEED"
        val PROJECT_DETAIL_EVERYTHING_ELSE: String = "PROJECT_DETAIL_EVERYTHING_ELSE"
        val PROJECT_DETAIL_PREPARATION: String = "PROJECT_DETAIL_PREPARATION"
        val PROJECT_DETAIL_CUT: String = "PROJECT_DETAIL_CUT"
        val PROJECT_DETAIL_ASSEMBLE: String = "PROJECT_DETAIL_ASSEMBLE"
        val PROJECT_DETAIL_CUSTOMIZE_BTN: String = "PROJECT_DETAIL_CUSTOMIZE_BTN"
        val PROJECT_DETAIL_MAKE_IT_BTN: String = "PROJECT_DETAIL_MAKE_IT_BTN"
        val PROJECT_DETAILS_DIFFICULTY_LEVEL: String = "PROJECT_DETAILS_DIFFICULTY_LEVEL"
        val PROJECT_DETAILS_COMPLETION_TIME: String = "PROJECT_DETAILS_COMPLETION_TIME"
        val PROJECT_DETAILS_PRICE: String = "PROJECT_DETAILS_PRICE"





    }

}